name: Embed Binaries

on:
  schedule:
    - cron: "59 23 * * *"
  workflow_dispatch:

permissions:
  issues: write

jobs:
  embed-binaries:
    uses: devantler-tech/workflows/.github/workflows/dotnet-embed-binaries.yaml@main
    secrets: inherit
    with:
      BINARY_NAME: k9s
      DOTNET_PROJECT_NAME: Devantler.K9sCLI
      SCRIPT_PATH: scripts/get-k9s-binary.sh
      # only get the first line
      VERSION_ARGS: version --short | awk '{print $2}' | head -n 1
